name: PingMOTD
main: com.modcrafting.pingmotd.PingMotd
version: 0.0.2
website: http://modcrafting.com
author: Deathmarine
description: >
             Displays a customizable MOTD when a ping request is sent.
commands:
  pingmotd:
    description: Command Access
    usage: /<command> - shows current version.
  pingmotdset:
    description: Command Access
    usage: /<command> - set ping message.
  pingmotdview:
    description: Command Access
    usage: /<command> - views the current message.