name: PingMOTD
main: com.modcrafting.pingmotd.PingMotd
version: 0.8
website: http://modcrafting.com
author: Deathmarine
description: >
             Displays a customizable MOTD when a ping request is sent.
commands:
  pmotd:
    description: Command Access
    usage: /<command> - handles all commands
permissions:
  pingmotd.*:
    default: op
    description: Allows full control
    children:
      pingmotd.view: true
      pingmotd.add: true
      pingmotd.del: true
      pingmotd.reload: true
  pingmotd.view:
    description: View all of the currently stored messages.
  pingmotd.add:
    description: Add to the list of messages.
  pingmotd.del:
    description: Remove from the list of messages.
  pingmotd.reload:
    description: Reload the configuration.
