name: PingMOTD
main: com.modcrafting.pingmotd.PingMotd
version: 0.7
website: http://modcrafting.com
author: Deathmarine
description: >
             Displays a customizable MOTD when a ping request is sent.
commands:
  pmotd:
    description: Command Access
    usage: /<command> - shows current version.
  pmotdadd:
    description: Command Access
    usage: /<command> - set ping message.
  pmotdview:
    description: Command Access
    usage: /<command> - views the current message.
  pmotdreload:
    description: Reloads the command
    usage: /<command> - Reloads the plugin